pipelines:
  default:
    - step:
        name: Instalar dependencias y ejecutar pruebas de Playwright
        image: node:18
        caches:
          - node
        script:
          - npm install
          - npx playwright install --with-deps
          - npx playwright test
        artifacts:
          - playwright-report/**
    - step:
        name: Ejecutar prueba de carga con Artillery
        image: node:18
        caches:
          - node
        script:
          - npm install -g artillery
          - artillery run artillery-config.yml --output reports/artillery-report.json
        artifacts:
          - reports/**